export const START_FETCHING_DASHBOARD_REVENUE =
  `redux/dashboard/START_FETCHING_DASHBOARD_REVENUE`;
export const SUCCESS_FETCHING_DASHBOARD_REVENUE =
  `redux/dashboard/SUCCESS_FETCHING_DASHBOARD_REVENUE`;
export const ERROR_FETCHING_DASHBOARD_REVENUE =
  `redux/dashboard/ERROR_FETCHING_DASHBOARD_REVENUE`;

export const START_FETCHING_DASHBOARD_TOTALORDER =
  `redux/dashboard/START_FETCHING_DASHBOARD_TOTALORDER`;
export const SUCCESS_FETCHING_DASHBOARD_TOTALORDER =
  `redux/dashboard/SUCCESS_FETCHING_DASHBOARD_TOTALORDER`;
export const ERROR_FETCHING_DASHBOARD_TOTALORDER =
  `redux/dashboard/ERROR_FETCHING_DASHBOARD_TOTALORDER`;

export const START_FETCHING_DASHBOARD_NEWORDER =
  `redux/dashboard/START_FETCHING_DASHBOARD_NEWORDER`;
export const SUCCESS_FETCHING_DASHBOARD_NEWORDER =
  `redux/dashboard/SUCCESS_FETCHING_DASHBOARD_NEWORDER`;
export const ERROR_FETCHING_DASHBOARD_NEWORDER =
  `redux/dashboard/ERROR_FETCHING_DASHBOARD_NEWORDER`;

export const START_FETCHING_DASHBOARD_BESTSELLING =
  `redux/dashboard/START_FETCHING_DASHBOARD_BESTSELLING`;
export const SUCCESS_FETCHING_DASHBOARD_BESTSELLING =
  `redux/dashboard/SUCCESS_FETCHING_DASHBOARD_BESTSELLING`;
export const ERROR_FETCHING_DASHBOARD_BESTSELLING =
  `redux/dashboard/ERROR_FETCHING_DASHBOARD_BESTSELLING`;

export const START_FETCHING_DASHBOARD_WORSTSELLING =
  `redux/dashboard/START_FETCHING_DASHBOARD_WORSTSELLING`;
export const SUCCESS_FETCHING_DASHBOARD_WORSTSELLING =
  `redux/dashboard/SUCCESS_FETCHING_DASHBOARD_WORSTSELLING`;
export const ERROR_FETCHING_DASHBOARD_WORSTSELLING =
  `redux/dashboard/ERROR_FETCHING_DASHBOARD_WORSTSELLING`;

export const START_FETCHING_DASHBOARD_SCHEDULE =
  `redux/dashboard/START_FETCHING_DASHBOARD_SCHEDULE`;
export const SUCCESS_FETCHING_DASHBOARD_SCHEDULE =
  `redux/dashboard/SUCCESS_FETCHING_DASHBOARD_SCHEDULE`;
export const ERROR_FETCHING_DASHBOARD_SCHEDULE =
  `redux/dashboard/ERROR_FETCHING_DASHBOARD_SCHEDULE`;